### ISSUE TITLE
Just a question about the code

### ISSUE THREAD

**Issue by lffg** [edge-js/lexer#1]
What is the function of this exclamation?
https://github.com/poppinss/edge-lexer/blob/develop/src/Tokenizer/index.ts#L69

```typescript
// [...]

const lines = this.template.split('\n')

while (lines.length) {
  this.line++
  this.processText(lines.shift()!)
  //                            ↑
  //                            |
}

// [...]
```

Thanks :)

**Comment by thetutlage** [comment]
Hey just saw the issue (maybe I am not watching the repo). You can read more about it here https://stackoverflow.com/questions/42273853/in-typescript-what-is-the-exclamation-mark-bang-operator-when-dereferenci
